import { ObjectDetection, PixelPlacement, Team } from '../app/team'

export const CyberPirates13737: Team = {
    number: 13737,
    name: "Belton Cyber Pirates",
    driveInfo: "Mecanum drive, field centric, very fast",
    armInfo: "Pivoting linear slide capable of reaching the third set line",
    intakeInfo: "Double claw able to precisely score and move pixels",
    teamProp: true,
    objectDetection: ObjectDetection.reliable,
    purplePlacement: PixelPlacement.correctPlacement,
    yellowPlacement: PixelPlacement.correctPlacement,
    autoWhites: 0,
    autoScore: 45,
    autoNotes: "Does not score yellow pixel on far side",
    mosaicsScored: 2,
    setLinesReached: 1,
    pixelsScored: 10,
    teleOpScore: 60,
    teleopNotes: "Usually focus on creating mosaics, exclusively grab from human player",
    canHang: true,
    hangTime: 2,
    droneScore: 20,
    endGameScore: 40,
    endGameNotes: "Very fast hanging, unreliable drone",
    averageScore: 145,
}

export const CyberPirates13399: Team = {
    number: 13399,
    name: "Belton Cyber Pirates",
    driveInfo: "Mecanum drive, stanndard drive, fast",
    armInfo: "Reverse double six bar able to reach the third set line",
    intakeInfo: "Double claw able to precisely score pixels",
    teamProp: true,
    objectDetection: ObjectDetection.mostlyReliable,
    purplePlacement: PixelPlacement.correctPlacement,
    yellowPlacement: PixelPlacement.sometimesCorrect,
    autoWhites: 0,
    autoScore: 35,
    autoNotes: "Does not score yellow pixel on far side",
    mosaicsScored: 2,
    setLinesReached: 1,
    pixelsScored: 10,
    teleOpScore: 60,
    teleopNotes: "Usually focus on creating mosaics, mostly grab from human player",
    canHang: true,
    hangTime: 10,
    droneScore: 20,
    endGameScore: 40,
    endGameNotes: "Somewhat quick hanging, unreliable drone",
    averageScore: 135,
}